--[[
    Definition of the GUI Style Stormcloud
]]

--[[ Pallette of colors ]]
local TEXT_COLOR = "#fff7d8"
local BACKGROUND_COLOR = "#313140"
local BACKGROUND_COLOR_DARKER = "#292934"
local BACKGROUND_COLOR_LIGHTER = "#424252"

qtcore.styles.stormcloud={
    TEXT_COLOR=TEXT_COLOR,
    BACKGROUND_COLOR=BACKGROUND_COLOR,
    BACKGROUND_COLOR_DARKER=BACKGROUND_COLOR_DARKER,
    BACKGROUND_COLOR_LIGHTER=BACKGROUND_COLOR_LIGHTER,
    BG_SIMPLE="GUI_Stormcloud_BG_0000_128x128_M4.png",
    BG_FANCY="GUI_Stormcloud_BG_1111_128x128_M8.png",
}

qts.scribe.register_style("qtcore:stormcloud", {
    container={
        texture="GUI_Stormcloud_BG_0000_128x128_M4.png",
        middle=8,
        padding={x=0.1,y=0.1},
    },
    horizontal_box={
        texture="GUI_Stormcloud_BG_1111_128x128_M8.png",
        middle=10,
        padding={x=0.2,y=0.2},
    },
    vertical_box={
        texture="GUI_Stormcloud_BG_1111_128x128_M8.png",
        middle=10,
        padding={x=0.2,y=0.2},
    },
    button={
        height=1,
        width=1,
        sound="gui_button",
        style_normal={
            background="GUI_Stormcloud_Button_normal_128x128_M8.png",
            background_middle=10,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_hovered={
            background="GUI_Stormcloud_Button_hovered_128x128_M8.png",
            background_middle=10,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_pressed={
            background="GUI_Stormcloud_Button_pressed_128x128_M8.png",
            background_middle=10,
            border=false,
            font={
                color=TEXT_COLOR,
                bold=true,
            },
            internal_offset={x=0,y=0},
        }
    },
    toggle_button={
        height=0.66,
        width=0.66,
        sound="gui_button",
        style_normal={
            background="GUI_Stormcloud_Toggle_off_normal_32x32.png",
            background_middle=16,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_hovered={
            background="GUI_Stormcloud_Toggle_off_hovered_32x32.png",
            background_middle=16,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_pressed={
            background="GUI_Stormcloud_Toggle_off_pressed_32x32.png",
            background_middle=16,
            border=false,
            font={
                color=TEXT_COLOR,
                bold=true,
            },
            internal_offset={x=0,y=0},
        },
        style_toggled_normal={
            background="GUI_Stormcloud_Toggle_on_normal_32x32.png",
            background_middle=16,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_toggled_hovered={
            background="GUI_Stormcloud_Toggle_on_hovered_32x32.png",
            background_middle=16,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_toggled_pressed={
            background="GUI_Stormcloud_Toggle_on_pressed_32x32.png",
            background_middle=16,
            border=false,
            font={
                color=TEXT_COLOR,
                bold=true,
            },
            internal_offset={x=0,y=0},
        },
        texture="",
        texture_pressed="",
        label=""
    },
    tab_header={
        name="",
        orientation=qts.scribe.orientation.HORIZONTAL,
        allignment=qts.scribe.allignment.TOP,
        tabs_allignment=qts.scribe.allignment.LEFT,
        style_normal={
            background="GUI_Stormcloud_Tab_top_off_normal_128x128_M8.png",
            background_middle=10,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_hovered={
            background="GUI_Stormcloud_Tab_top_off_hovered_128x128_M8.png",
            background_middle=10,
            border=false,
            font={
                color=TEXT_COLOR,
            },
            internal_offset={x=0,y=0},
        },
        style_pressed={
            background="GUI_Stormcloud_Tab_top_off_pressed_128x128_M8.png",
            background_middle=10,
            border=false,
            font={
                color=TEXT_COLOR,
                bold=true,
            },
            internal_offset={x=0,y=0},
        }
    },
    inventory_colors={
        background_color="#00000069",
        background_hover_color=BACKGROUND_COLOR_LIGHTER,
        border_color=BACKGROUND_COLOR_DARKER,
        tooltip_color=BACKGROUND_COLOR_DARKER,
        tooltip_text_color=TEXT_COLOR
    },
    text={
        font={
            color=TEXT_COLOR
        }
    },
--this comment is to remove the highliting for the "model" and "texture" requiments
---@diagnostic disable-next-line: missing-fields
    model={
        background_color=BACKGROUND_COLOR_DARKER,
    },
    tooltip_colors={
        fgcolor=TEXT_COLOR,
        bgcolor=BACKGROUND_COLOR_DARKER
    },
    use_minetest_prepend=false,
})