#if !defined ENUM_ENTRY
#define ENUM_ENTRY(name, value, desc) unsigned int name = value;
#endif 

ENUM_ENTRY(KEY_UNKNOWN,           0x0,   "Unknown Key")
ENUM_ENTRY(KEY_LBUTTON,           0x01,  "Left mouse button")
ENUM_ENTRY(KEY_RBUTTON,           0x02,  "Right mouse button")
ENUM_ENTRY(KEY_CANCEL,            0x03,  "Control-break processing")
ENUM_ENTRY(KEY_MBUTTON,           0x04,  "Middle mouse button (three-button mouse)")
ENUM_ENTRY(KEY_XBUTTON1,          0x05,  "Windows 2000/XP: X1 mouse button")
ENUM_ENTRY(KEY_XBUTTON2,          0x06,  "Windows 2000/XP: X2 mouse button")
ENUM_ENTRY(KEY_BACK,              0x08,  "BACKSPACE key")
ENUM_ENTRY(KEY_TAB,               0x09,  "TAB key")
ENUM_ENTRY(KEY_CLEAR,             0x0C,  "CLEAR key")
ENUM_ENTRY(KEY_RETURN,            0x0D,  "ENTER key")
ENUM_ENTRY(KEY_SHIFT,             0x10,  "SHIFT key")
ENUM_ENTRY(KEY_CONTROL,           0x11,  "CTRL key")
ENUM_ENTRY(KEY_MENU,              0x12,  "ALT key")
ENUM_ENTRY(KEY_PAUSE,             0x13,  "PAUSE key")
ENUM_ENTRY(KEY_CAPITAL,           0x14,  "CAPS LOCK key")
ENUM_ENTRY(KEY_KANA,              0x15,  "IME Kana mode")
//ENUM_ENTRY(KEY_HANGUEL,           0x15,  "IME Hanguel mode (maintained for compatibility use KEY_HANGUL)")
//ENUM_ENTRY(KEY_HANGUL,            0x15,  "IME Hangul mode")
ENUM_ENTRY(KEY_JUNJA,             0x17,  "IME Junja mode")
ENUM_ENTRY(KEY_FINAL,             0x18,  "IME final mode")
ENUM_ENTRY(KEY_HANJA,             0x19,  "IME Hanja mode")
//ENUM_ENTRY(KEY_KANJI,             0x19,  "IME Kanji mode")
ENUM_ENTRY(KEY_ESCAPE,            0x1B,  "ESC key")
ENUM_ENTRY(KEY_CONVERT,           0x1C,  "IME convert")
ENUM_ENTRY(KEY_NONCONVERT,        0x1D,  "IME nonconvert")
ENUM_ENTRY(KEY_ACCEPT,            0x1E,  "IME accept")
ENUM_ENTRY(KEY_MODECHANGE,        0x1F,  "IME mode change request")
ENUM_ENTRY(KEY_SPACE,             0x20,  "SPACEBAR")
ENUM_ENTRY(KEY_PRIOR,             0x21,  "PAGE UP key")
ENUM_ENTRY(KEY_NEXT,              0x22,  "PAGE DOWN key")
ENUM_ENTRY(KEY_END,               0x23,  "END key")
ENUM_ENTRY(KEY_HOME,              0x24,  "HOME key")
ENUM_ENTRY(KEY_LEFT,              0x25,  "LEFT ARROW key")
ENUM_ENTRY(KEY_UP,                0x26,  "UP ARROW key")
ENUM_ENTRY(KEY_RIGHT,             0x27,  "RIGHT ARROW key")
ENUM_ENTRY(KEY_DOWN,              0x28,  "DOWN ARROW key")
ENUM_ENTRY(KEY_SELECT,            0x29,  "SELECT key")
ENUM_ENTRY(KEY_PRINT,             0x2A,  "PRINT key")
ENUM_ENTRY(KEY_EXECUT,            0x2B,  "EXECUTE key")
ENUM_ENTRY(KEY_SNAPSHOT,          0x2C,  "PRINT SCREEN key")
ENUM_ENTRY(KEY_INSERT,            0x2D,  "INS key")
ENUM_ENTRY(KEY_DELETE,            0x2E,  "DEL key")
ENUM_ENTRY(KEY_HELP,              0x2F,  "HELP key")
ENUM_ENTRY(KEY_KEY_0,             0x30,  "0 key")
ENUM_ENTRY(KEY_KEY_1,             0x31,  "1 key")
ENUM_ENTRY(KEY_KEY_2,             0x32,  "2 key")
ENUM_ENTRY(KEY_KEY_3,             0x33,  "3 key")
ENUM_ENTRY(KEY_KEY_4,             0x34,  "4 key")
ENUM_ENTRY(KEY_KEY_5,             0x35,  "5 key")
ENUM_ENTRY(KEY_KEY_6,             0x36,  "6 key")
ENUM_ENTRY(KEY_KEY_7,             0x37,  "7 key")
ENUM_ENTRY(KEY_KEY_8,             0x38,  "8 key")
ENUM_ENTRY(KEY_KEY_9,             0x39,  "9 key")
ENUM_ENTRY(KEY_KEY_A,             0x41,  "A key")
ENUM_ENTRY(KEY_KEY_B,             0x42,  "B key")
ENUM_ENTRY(KEY_KEY_C,             0x43,  "C key")
ENUM_ENTRY(KEY_KEY_D,             0x44,  "D key")
ENUM_ENTRY(KEY_KEY_E,             0x45,  "E key")
ENUM_ENTRY(KEY_KEY_F,             0x46,  "F key")
ENUM_ENTRY(KEY_KEY_G,             0x47,  "G key")
ENUM_ENTRY(KEY_KEY_H,             0x48,  "H key")
ENUM_ENTRY(KEY_KEY_I,             0x49,  "I key")
ENUM_ENTRY(KEY_KEY_J,             0x4A,  "J key")
ENUM_ENTRY(KEY_KEY_K,             0x4B,  "K key")
ENUM_ENTRY(KEY_KEY_L,             0x4C,  "L key")
ENUM_ENTRY(KEY_KEY_M,             0x4D,  "M key")
ENUM_ENTRY(KEY_KEY_N,             0x4E,  "N key")
ENUM_ENTRY(KEY_KEY_O,             0x4F,  "O key")
ENUM_ENTRY(KEY_KEY_P,             0x50,  "P key")
ENUM_ENTRY(KEY_KEY_Q,             0x51,  "Q key")
ENUM_ENTRY(KEY_KEY_R,             0x52,  "R key")
ENUM_ENTRY(KEY_KEY_S,             0x53,  "S key")
ENUM_ENTRY(KEY_KEY_T,             0x54,  "T key")
ENUM_ENTRY(KEY_KEY_U,             0x55,  "U key")
ENUM_ENTRY(KEY_KEY_V,             0x56,  "V key")
ENUM_ENTRY(KEY_KEY_W,             0x57,  "W key")
ENUM_ENTRY(KEY_KEY_X,             0x58,  "X key")
ENUM_ENTRY(KEY_KEY_Y,             0x59,  "Y key")
ENUM_ENTRY(KEY_KEY_Z,             0x5A,  "Z key")
ENUM_ENTRY(KEY_LWIN,              0x5B,  "Left Windows key (Microsoft� Natural� keyboard)")
ENUM_ENTRY(KEY_RWIN,              0x5C,  "Right Windows key (Natural keyboard)")
ENUM_ENTRY(KEY_APPS,              0x5D,  "Applications key (Natural keyboard)")
ENUM_ENTRY(KEY_SLEEP,             0x5F,  "Computer Sleep key")
ENUM_ENTRY(KEY_NUMPAD0,           0x60,  "Numeric keypad 0 key")
ENUM_ENTRY(KEY_NUMPAD1,           0x61,  "Numeric keypad 1 key")
ENUM_ENTRY(KEY_NUMPAD2,           0x62,  "Numeric keypad 2 key")
ENUM_ENTRY(KEY_NUMPAD3,           0x63,  "Numeric keypad 3 key")
ENUM_ENTRY(KEY_NUMPAD4,           0x64,  "Numeric keypad 4 key")
ENUM_ENTRY(KEY_NUMPAD5,           0x65,  "Numeric keypad 5 key")
ENUM_ENTRY(KEY_NUMPAD6,           0x66,  "Numeric keypad 6 key")
ENUM_ENTRY(KEY_NUMPAD7,           0x67,  "Numeric keypad 7 key")
ENUM_ENTRY(KEY_NUMPAD8,           0x68,  "Numeric keypad 8 key")
ENUM_ENTRY(KEY_NUMPAD9,           0x69,  "Numeric keypad 9 key")
ENUM_ENTRY(KEY_MULTIPLY,          0x6A,  "Multiply key")
ENUM_ENTRY(KEY_ADD,               0x6B,  "Add key")
ENUM_ENTRY(KEY_SEPARATOR,         0x6C,  "Separator key")
ENUM_ENTRY(KEY_SUBTRACT,          0x6D,  "Subtract key")
ENUM_ENTRY(KEY_DECIMAL,           0x6E,  "Decimal key")
ENUM_ENTRY(KEY_DIVIDE,            0x6F,  "Divide key")
ENUM_ENTRY(KEY_F1,                0x70,  "F1 key")
ENUM_ENTRY(KEY_F2,                0x71,  "F2 key")
ENUM_ENTRY(KEY_F3,                0x72,  "F3 key")
ENUM_ENTRY(KEY_F4,                0x73,  "F4 key")
ENUM_ENTRY(KEY_F5,                0x74,  "F5 key")
ENUM_ENTRY(KEY_F6,                0x75,  "F6 key")
ENUM_ENTRY(KEY_F7,                0x76,  "F7 key")
ENUM_ENTRY(KEY_F8,                0x77,  "F8 key")
ENUM_ENTRY(KEY_F9,                0x78,  "F9 key")
ENUM_ENTRY(KEY_F10,               0x79,  "F10 key")
ENUM_ENTRY(KEY_F11,               0x7A,  "F11 key")
ENUM_ENTRY(KEY_F12,               0x7B,  "F12 key")
ENUM_ENTRY(KEY_F13,               0x7C,  "F13 key")
ENUM_ENTRY(KEY_F14,               0x7D,  "F14 key")
ENUM_ENTRY(KEY_F15,               0x7E,  "F15 key")
ENUM_ENTRY(KEY_F16,               0x7F,  "F16 key")
ENUM_ENTRY(KEY_F17,               0x80,  "F17 key")
ENUM_ENTRY(KEY_F18,               0x81,  "F18 key")
ENUM_ENTRY(KEY_F19,               0x82,  "F19 key")
ENUM_ENTRY(KEY_F20,               0x83,  "F20 key")
ENUM_ENTRY(KEY_F21,               0x84,  "F21 key")
ENUM_ENTRY(KEY_F22,               0x85,  "F22 key")
ENUM_ENTRY(KEY_F23,               0x86,  "F23 key")
ENUM_ENTRY(KEY_F24,               0x87,  "F24 key")
ENUM_ENTRY(KEY_NUMLOCK,           0x90,  "NUM LOCK key")
ENUM_ENTRY(KEY_SCROLL,            0x91,  "SCROLL LOCK key")
ENUM_ENTRY(KEY_LSHIFT,            0xA0,  "Left SHIFT key")
ENUM_ENTRY(KEY_RSHIFT,            0xA1,  "Right SHIFT key")
ENUM_ENTRY(KEY_LCONTROL,          0xA2,  "Left CONTROL key")
ENUM_ENTRY(KEY_RCONTROL,          0xA3,  "Right CONTROL key")
ENUM_ENTRY(KEY_LMENU,             0xA4,  "Left MENU key")
ENUM_ENTRY(KEY_RMENU,             0xA5,  "Right MENU key")
ENUM_ENTRY(KEY_BROWSER_BACK,      0xA6,  "Browser Back key")
ENUM_ENTRY(KEY_BROWSER_FORWARD,   0xA7,  "Browser Forward key")
ENUM_ENTRY(KEY_BROWSER_REFRESH,   0xA8,  "Browser Refresh key")
ENUM_ENTRY(KEY_BROWSER_STOP,      0xA9,  "Browser Stop key")
ENUM_ENTRY(KEY_BROWSER_SEARCH,    0xAA,  "Browser Search key ")
ENUM_ENTRY(KEY_BROWSER_FAVORITES, 0xAB,  "Browser Favorites key")
ENUM_ENTRY(KEY_BROWSER_HOME,      0xAC,  "Browser Start and Home key")
ENUM_ENTRY(KEY_VOLUME_MUTE,       0xAD,  "Volume Mute key")
ENUM_ENTRY(KEY_VOLUME_DOWN,       0xAE,  "Volume Down key")
ENUM_ENTRY(KEY_VOLUME_UP,         0xAF,  "Volume Up key")
ENUM_ENTRY(KEY_MEDIA_NEXT_TRACK,  0xB0,  "Next Track key")
ENUM_ENTRY(KEY_MEDIA_PREV_TRACK,  0xB1,  "Previous Track key")
ENUM_ENTRY(KEY_MEDIA_STOP,        0xB2,  "Stop Media key")
ENUM_ENTRY(KEY_MEDIA_PLAY_PAUSE,  0xB3,  "Play/Pause Media key")
ENUM_ENTRY(KEY_OEM_1,             0xBA,  "for US    \";:\"")
ENUM_ENTRY(KEY_PLUS,              0xBB,  "Plus Key   \"+\"")
ENUM_ENTRY(KEY_COMMA,             0xBC,  "Comma Key  \",\"")
ENUM_ENTRY(KEY_MINUS,             0xBD,  "Minus Key  \"-\"")
ENUM_ENTRY(KEY_PERIOD,            0xBE,  "Period Key \".\"")
ENUM_ENTRY(KEY_OEM_2,             0xBF,  "for US    \"/?\"")
ENUM_ENTRY(KEY_OEM_3,             0xC0,  "for US    \"`~\"")
ENUM_ENTRY(KEY_OEM_4,             0xDB,  "for US    \"[{\"")
ENUM_ENTRY(KEY_OEM_5,             0xDC,  "for US    \"\\|\"")
ENUM_ENTRY(KEY_OEM_6,             0xDD,  "for US    \"]}\"")
ENUM_ENTRY(KEY_OEM_7,             0xDE,  "for US    \"'\"\"")
ENUM_ENTRY(KEY_OEM_8,             0xDF,  "None")
ENUM_ENTRY(KEY_OEM_AX,            0xE1,  "for Japan \"AX\"")
ENUM_ENTRY(KEY_OEM_102,           0xE2,  "\"<>\" or \"\\|\"")
ENUM_ENTRY(KEY_ATTN,              0xF6,  "Attn key")
ENUM_ENTRY(KEY_CRSEL,             0xF7,  "CrSel key")
ENUM_ENTRY(KEY_EXSEL,             0xF8,  "ExSel key")
ENUM_ENTRY(KEY_EREOF,             0xF9,  "Erase EOF key")
ENUM_ENTRY(KEY_PLAY,              0xFA,  "Play key")
ENUM_ENTRY(KEY_ZOOM,              0xFB,  "Zoom key")
ENUM_ENTRY(KEY_PA1,               0xFD,  "PA1 key")
ENUM_ENTRY(KEY_OEM_CLEAR,         0xFE,  "Clear key")
ENUM_ENTRY(KEY_NONE,			  0xFF,  "usually no key mapping, but some laptops use it for fn key")
ENUM_ENTRY(KEY_MAXINDEX,		  0x100,  "length of an array to hold all the keys")